title: Lviv JavaClub
description: > #
  Let's become the best together
url: "https://lvivjavaclub.github.io/"

githuburl: https://github.com/lvivJavaClub

# Google services
google_analytics: UA-1596745-41

theme: jekyll-theme-cayman
paginate: 5
plugins:
  - jekyll-feed
