title: Lviv JavaClub
description: > #
  Let's become the best together
url: "https://lvivjavaclub.github.io/"


site:
  github:
    is_project_page: true
    repository_url: https://github.com/lvivJavaClub

# Google services
google_analytics: UA-1596745-41

theme: jekyll-theme-cayman
paginate: 1
plugins:
  - jekyll-feed
