name: Site build
on: 
  workflow_dispatch:
    inputs:
      post_title:
        description: 'Used for filename and post.sh name. The space will be replaced by `-` inv the file name.'
        default: ''
        required: true
      post_body:
        description: 'Use GitHub MD format'
        default: 'This week on Java Club we will review the'
        required: true
      room:
        description: 'Choose place: Online|in Jamaica (room 223)|in Spain (room 426)'
        default: 'Online'
        required: true
      tags:
        description: 'Capitalized Tags separated by commas'
        default: ''
        required: true
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    
    env:
      FILENAME: ./_posts/$(date +'%Y-%m-%d')-$( echo 'Event#${{ github.event.inputs.post_title }}' | sed -r 's/[# ]+/-/g' ).md
      MESSAGE: ${{ github.event.inputs.post_body }}
      POST: |
        ---
        layout: post
        title:  \"Event#${{ github.event.inputs.post_title }}\"
        image: /images/default.jpg
        tags: [${{ github.event.inputs.tags }}]
        date: $(date +'%Y-%m-%d %H:%M:%S %z')
        video: 
        ---

        ${{ github.event.inputs.post_body }}
      JOIN: Join us next Thursday, at 10:00 ${{ github.event.inputs.room }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Calculate event number
        run: |
          lastEvent=$(ls -LR1 | sed -E 's/[0-9]{4}-[0-9]{2}-[0-9]{2}-//;s/Event-//;s/-.*//;s/.md//' | sort -n | tail -1)
          nextEvent=$((lastEvent+1))
          echo "next_event=nextEvent" >> $GITHUB_ENV
          
      - name: Create post file
        run: |
          echo "${{ env.next_event }}"
            

